# 🔗 Links:
# Source file: https://github.com/Tulpar-Yazilim/expo-starter-template/blob/master/.github/actions/setup-node-yarn-install/action.yml
# Composite actions docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# ✍️ Description:
# This is a composite action, which means it can be used in other actions.
# It is used in almost all workflows to set up the environment and install dependencies.
# Updating the Node version in .nvmrc will be reflected in all workflows automatically.

# 👀 Example usage:
#       - name : 📦 Setup Node + YARN + install deps
#         uses: ./.github/actions/setup-node-yarn-install

name: 'Setup  Node + YARN + Install Dependencies'
description: 'Setup  Node + YARN + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: mskelton/setup-yarn@v3
      name: Install yarn

    - uses: actions/setup-node@v4
      name: Install Node.js
      with:
        node-version-file: '.nvmrc'

    - name: 📦 Cache yarn dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: yarn-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-

    - name: 📦 Install Project Dependencies
      run: yarn install --frozen-lockfile
      shell: bash
