#!/bin/sh

changed() {
  git diff --name-only HEAD@{1} HEAD | grep -q "^$1"
}

echo "🔍 Checking for changes in yarn.lock..."

if changed "yarn.lock"; then
  echo "📦 yarn.lock has changed."
  echo "👉 Please run 'yarn install' to sync your dependencies."
else
  echo "✅ Dependencies are up to date."
fi

echo
echo "ℹ️ If necessary, you can run:"
echo "   yarn prebuild"
echo

exit 0
