name: SonarQube analysis

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - master
      - staging
      - qa
      - development

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + YARN + install deps
        uses: ./.github/actions/setup-node-yarn-install

      - name: Run Tests
        run: yarn test:ci

      - name: SonarQube Scan
        if: env.SONAR_TOKEN != '' && env.SONAR_HOST_URL != '' && env.SONAR_PROJECT != ''
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          args: >
            -Dsonar.sonar.sources=./src 
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectBaseDir=.
            -Dsonar.verbose=false
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
            -Dsonar.sonar.sourceEncoding=UTF-8
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/node_modules/**,**/storage/**,**/**.config.js,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/icons/**,**/docs/**,**/cli/**,**/android/**,**/ios/**,env.js,app.config.ts,jest-setup.ts
            -Dsonar.exclusions=**/docs/**,**/__mocks__/**,**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,app.config.ts,jest-setup.ts

      - name: ℹ️ SonarQube configuration missing
        if: env.SONAR_TOKEN == '' || env.SONAR_HOST_URL == '' || env.SONAR_PROJECT == ''
        run: echo "⚠️ SonarQube secrets not configured. To enable SonarQube analysis, add SONAR_TOKEN, SONAR_URL, and SONAR_PROJECT to repository secrets."